config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/
  scope "(:locale)", locale: LOCALES do
    resources :rooms do
      resources :reviews, only: [:create, :update], module: :rooms
    end
    resources :users
  end
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  get '/:locale' => 'home#index', locale: LOCALES
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  POINTS = (1..5).to_a
  belongs_to :user
  belongs_to :room, counter_cache: true
  validates :user_id, uniqueness: { scope: :room_id }
  validates :points, :user_id, :room_id, presence: true
  validates :points, inclusion: { in: POINTS }

  def self.stars
    (average(:points) || 0).round
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
  extend FriendlyId
  validates :title, :location, :description, :slug, presence: true
  validates :description, length: { minimum: 5 }
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :reviewed_rooms, through: :reviews, source: :room
  scope :most_recent, -> { order('created_at DESC') }
  friendly_id :title, use: [:slugged, :history]
  mount_uploader :picture, PictureUploader

  def self.search(query)
    if query.present?
      where(['location ILIKE :query OR title ILIKE :query OR description ILIKE :query', query: "%#{query}%"])
    else
      Room.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rooms, dependent: :destroy
    has_many :reviews, dependent: :destroy
    scope :most_recent, -> { order('created_at DESC') }
    scope :confirmed, -> { where.not(confirmed_at: nil) }

    def self.authenticate(email, password)
      user = confirmed.find_by(email: email)
      if user.present?
        user.authenticate(password)
      end
    end

    #EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    validates :email, :full_name, :location, :bio, presence: true
    validates :bio, length: { in: 5..20 }, allow_blank: false
    #validate :email_format
    validates :email, uniqueness: true
    has_secure_password

    before_create do |user|
      user.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
      return if confirmed?

      self.confirmed_at = Time.current
      self.confirmation_token = ''
      save!
    end

    def confirmed?
      confirmed_at.present?
    end
    private

    def email_format
      errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
    end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model
  attr_accessor :email, :password
  validates :email, :password, presence: true

  def initialize(session, attributes={})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate
    user = User.authenticate(@email, @password)
    
    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action do
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options
      { locale: I18n.locale }
    end

    delegate :current_user, :user_signed_in?, to: :user_session
    helper_method :current_user, :user_signed_in?


    def user_session
      UserSession.new(session)
    end

    def require_authentication
      unless user_signed_in?
        redirect_to new_user_sessions_path,
          alert: t('flash.alert.needs_login')
      end
    end

    def require_no_authentication
      if user_signed_in?
        redirect_to root_path,
          notice: t('flash.notice.already_logged_in')
      end
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])

    if user.present?
      user.confirm!
      redirect_to user,
        notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.take(10)
  end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
  before_action :require_authentication

  def create
    review = room.reviews.find_or_initialize_by(user_id: current_user.id)
    review.update!(review_params)
    head :ok
  end

  def update
    create
  end

  private

  def room
    @room ||= Room.find(params[:room_id])
  end

  def review_params
    params.require(:review).permit(:points)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_authentication, only: [:new, :create, :edit, :update, :destroy]
  PER_PAGE = 10

  def index
    @search_query = params[:q]
    rooms = Room.search(@search_query).page(params[:page]).per(PER_PAGE)
    @rooms = RoomCollectionPresenter.new(rooms.most_recent, self)
  end

  def show
    room_model = Room.friendly.find(params[:id])
    @room = RoomPresenter.new(room_model, self)
  end

  def new
    @room = current_user.rooms.build
  end

  def edit
    @room = current_user.rooms.friendly.find(params[:id])
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render action: "new"    
    end
  end

  def update
    @room = current_user.rooms.friendly.find(params[:id])
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render action: "edit"
    end
  end

  def destroy
    @room = current_user.rooms.friendly.find(params[:id])
    @room.destroy
    redirect_to rooms_url
  end

  private
  
  def room_params
    params.require(:room).permit(:title, :location, :description, :picture)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy
  
  def new
    @user_session = UserSession.new(session)
  end

  def create
    @user_session = UserSession.new(session, params[:user_session])
    if @user_session.authenticate
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_no_authentication, only: [:new, :create]
    before_action :can_change, only: [:edit, :update]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            SignupMailer.confirm_email(@user).deliver
            redirect_to @user,
                        notice: 'Cadastrado com sucesso!'
        else
            render action: :new
        end
    end
    
    def user_params
        params.require(:user).permit(:user_id, :full_name, :location, :email, :password, :password_confirmation, :bio)
    end

    def can_change
        unless user_signed_in? && current_user == user
            redirect_to user_path(params[:id])
        end
    end

    def user
        @user ||= User.find(params[:id])
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user,
                        notice: 'Alterações salvas com sucesso!'
        else
            render action: :edit
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
        :div,
        model.errors[attribute].first,
        class: 'error_message'
        )
      end
    end
  end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<h1 style="color:darkgreen">Quartos recém postados</h1>
<ul>
  <% @rooms.each do |room| %>
    <li><%= link_to t('rooms.complete_name', title: room.title, location: room.location ), room %></li>
  <% end %>
</ul>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %> </li>
    <li><%= link_to t('layout.rooms'), rooms_path %> </li>
    <li>
      <%= link_to t('layout.my_profile'), user_path(current_user) %>
    </li>
    <li>
      <%= link_to t('layout.signout'), user_sessions_path, method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %> </li>
    <li><%= link_to t('layout.signup'), new_user_path %> </li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColchoNet do Rodrigo</title>
      <link href="https://fonts.googleapis.com/css?family=Old+Standard+TT&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <header>
        <div id="header-wrap">
          <h1><%= link_to "ColchoNet do Rodrigo", root_path, style: 'color:#00008b;' %></h1>
          <% if user_signed_in? %>
            <%= render 'layouts/user_navbar' %>
          <% else %>
            <%= render 'layouts/visitor_navbar' %>
          <% end %>
        </div>
      </header>

      <div id="content">
        <% if notice.present? %>
          <p id="notice"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p id="alert"><%= alert %></p>
        <% end %>

        <%= yield %>
      </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <p>
    <%= form.label :picture %>
    <%= form.file_field :picture %>
    <%= error_tag @room, :picture %>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    <%= t. '.stars', average: room.stars, max: room.review_points.max, count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point %>
      <%= f.label :points, value: point do %>
        <i class="icon-star"></i>
      <% end %>
    <% end %>

    <%= f.submit %>
    
  <% end %>
  
<% else %>
  <span class="login_required">
    <%= t('.login_to_review') %>
  </span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
    <h2><%= link_to highlight(room.title, @search_query), room.route %></h2>

    <%= render partial: 'review', locals: {room: room} %>

    <span class="created">
        <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
    </span>
    <p>
        <span class="location">
            <%= link_to highlight(room.location, @search_query), "https://maps.google.com/?q=#{room.location}", target: :blank %>
        </span>
    </p>
    <div class="room-description">
      <%= link_to(image_tag(room.thumb_url), room.picture_url) if room.has_picture? %>
      <p><%= highlight(room.description || '', @search_query) %></p>
    </div>
    <% if belongs_to_user(room) %>
      <ul>
        <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
        <li><%= link_to t('.destroy'), room_path(room.route), method: :delete, data: {confirm: t('dialogs.destroy')}%></li>
      </ul>
    <% end %>
</article>

app/views/rooms/_search.html.erb
<%= form_tag rooms_path, method: :get, class: 'search' do %>
  <%= text_field_tag :q, @search_query, placeholder: t('.search_for') %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', room: @room %>

<%= link_to t('links.show'), @room %>
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/index.html.erb
<%= render 'search' %>

<h1>
  <% if @search_query.present? %>
    <%= t '.search_results' %>
  <% else %>
    <%= t '.title' %>
  <% end %>
</h1>

<%= render @rooms %>

<%= paginate @rooms %>

app/views/rooms/new.html.erb
<h1><%= t 'rooms.new.title' %></h1>
<%= render 'form', room: @room %>
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @user_session.errors.has_key? :base %>
  <div id="error_explanation">
    <%= @user_session.errors[:base].join(', ') %>
  </div>
<% end %>

<%= form_for @user_session do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user_session, :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user_session, :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %></p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <%= t 'general.form_error' %>
   </div>
<% end %>

<%= form_for @user do |f| %>
<p>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <%= error_tag @user, :full_name %>
</p>
<p>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @user, :location %>
</p>
<p>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= error_tag @user, :email %>
</p>
<p>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= error_tag @user, :password %>
</p>
<p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= error_tag @user, :password_confirmation %>
</p>
<p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
    <%= error_tag @user, :bio %>

</p>
<p>
  <%= f.submit class:'botao' %>
</p>
<% end %>

app/views/users/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    
    <% room.stars.times do %>
      <span class="star filled_star"></span>
    <% end %>

    <% (room.review_points.max - room.stars).times do %>
      <span class="star empty_star"></span>
    <% end %>

    <%= t '.stars', count: room.total_reviews %>
  <% end %>
</section>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h2>Perfil: <%= @user.full_name %> </h2>
<ul>
<li>Localização: <%= @user.location %> </li>
<li>Bio: <%= @user.bio %> </li>
</ul>
<%= link_to 'Editar Perfil', edit_user_path(@user) %>